name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: descargar-proyecto
        uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: instalar-dependencias
        run: npm ci
      - name: ejecutar-tests
        run: npm run test
      - name: linting
        run: npm run lint
      - name: construir-proyecto
        run: npm run build
      - name: Finalizar-deploy
        run: echo "Deploy exitoso"